name: Build and deploy v2train-be-microservice to AKS

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
  CONTAINER_NAME: "backend-api"
  RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
  CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
  DEPLOYMENT_MANIFEST_PATH: "./k8s"

jobs:
  buildImage:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # or '16', '20', 'lts/*', etc.
          cache: 'npm'        # This caches npm dependencies for faster builds

      # Install Node.js dependencies
      - name: Install dependencies
        run: npm ci  # Use 'npm ci' instead of 'npm install' for CI/CD
      

      # Logs in with your Azure credentials
      - name: Azure login
        id: azure-login
        continue-on-error: true
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}      
        env:
          ACTIONS_STEP_DEBUG: true
     
      # Builds and pushes an image up to your Azure Container Registry
      - name: Build and push image to ACR
        run: |
          az acr build --image ${{ env.CONTAINER_NAME }}:${{ github.sha }} --registry ${{ secrets.CONTAINER_REGISTRY }} -g ${{ secrets.RESOURCE_GROUP }} .

  deploy:
    permissions:
      actions: read
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    needs: [buildImage]
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v4

      # Logs in with your Azure credentials
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      # Use kubelogin to configure your kubeconfig for Azure auth
      - name: Set up kubelogin for non-interactive login
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.25'

      # Retrieves your Azure Kubernetes Service cluster's kubeconfig file
      - name: Get K8s context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}
          admin: 'false'
          use-kubelogin: 'true'

      - name: Deploy application
        env:
          CONTAINER_REGISTRY: ${{ env.CONTAINER_REGISTRY }}
        run: |
          for file in k8s/*.yaml; do
            echo "Deploying $file..."
            az aks command invoke \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --name ${{ env.CLUSTER_NAME }} \
              --command "kubectl apply -f - <<EOF
          $(envsubst < $file)
          EOF"
          done
